# For dev-cetera.com
# Version: 1

include: package:lints/recommended.yaml

## ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

linter:
  rules:
    avoid_web_libraries_in_flutter: true
    camel_case_types: false
    constant_identifier_names: false
    file_names: false
    library_private_types_in_public_api: false
    non_constant_identifier_names: false
    omit_local_variable_types: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_function_declarations_over_variables: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unawaited_futures: true
    unnecessary_this: true

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    # - '**.g.dart'

  errors:
    always_declare_return_types: error
    avoid_renaming_method_parameters: error
    avoid_type_to_string: error
    close_sinks: error
    collection_methods_unrelated_type: error
    depend_on_referenced_packages: error
    flutter_style_todos: error
    invalid_override_of_non_virtual_member: error
    invalid_use_of_protected_member: error
    missing_return: error
    no_leading_underscores_for_local_identifiers: error
    prefer_final_in_for_each: error
    prefer_relative_imports: error
    record_literal_one_positional_no_trailing_comma: error
    unnecessary_new: error
    unrelated_type_equality_checks: error
    unused_label: ignore
    use_key_in_widget_constructors: error

formatter:
  trailing_commas: preserve
